package provenance

import (
	"os"
	"path/filepath"
	"testing"
)

// The fixtures in testdata/ are generated by Scriptorium's own renderer — see
// its spec/provenance/. They are not hand-written, because a hand-written
// approximation of the producer's output tests this parser against a format
// nobody actually emits.
//
// This is a wire contract between two repositories in two languages, with
// nothing at build time to keep them agreeing. Scriptorium writes the marker
// and the NOTE block; moansubs decides from them whether an upload is
// machine-generated. If the producer changes shape and this parser is not
// updated, generated uploads silently lose their disclosure flag — the exact
// failure this package exists to prevent, and one that fails open.
//
// Regenerating: run Scriptorium's spec/provenance/generate.py and copy the
// result here. Fixtures are append-only. An old format stays supported
// forever because files carrying it exist in the wild forever, so never edit
// an existing fixture — add a new one.

func load(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	return b
}

func TestConformanceTranscript(t *testing.T) {
	generated, p := Detect(load(t, "transcript.vtt"))
	if !generated {
		t.Fatal("a Scriptorium transcript was not detected as generated")
	}
	if p == nil {
		t.Fatal("detected as generated but no provenance was parsed")
	}
	if p.Tool != "scriptorium" {
		t.Errorf("Tool = %q, want scriptorium", p.Tool)
	}
	if p.Version != "1.4.0" || p.ASRModel != "large-v3" {
		t.Errorf("Version/ASRModel = %q/%q", p.Version, p.ASRModel)
	}
	if p.Src != "en" || p.Dst != "en" {
		t.Errorf("Src/Dst = %q/%q", p.Src, p.Dst)
	}
	// The producer names this key "generated", not "date".
	if p.Date != "2026-08-07" {
		t.Errorf("Date = %q, want 2026-08-07", p.Date)
	}
	if p.Cues != 3 {
		t.Errorf("Cues = %d, want 3", p.Cues)
	}
	if p.Media != "oshash:0123456789abcdef" {
		t.Errorf("Media = %q", p.Media)
	}
	// A transcript is not a translation, however it was produced.
	if p.Translated() {
		t.Error("Translated() = true for a plain transcript")
	}
}

// The producer emits `"mt_model": null` rather than omitting the key when no
// translation ran. Go leaves a non-pointer string untouched on a JSON null, so
// this works — but by a property of encoding/json rather than by agreement.
// Pinning it here means a future change to a *string, or to the producer
// omitting the key, is caught rather than silently flipping Translated().
func TestConformanceNullMTModelIsNotTranslated(t *testing.T) {
	_, p := Detect(load(t, "transcript.vtt"))
	if p == nil {
		t.Fatal("no provenance parsed")
	}
	if p.MTModel != "" {
		t.Errorf("MTModel = %q, want empty for a JSON null", p.MTModel)
	}
	if p.Translated() {
		t.Error("Translated() = true when mt_model was null")
	}
}

func TestConformanceTranslation(t *testing.T) {
	generated, p := Detect(load(t, "translation.vtt"))
	if !generated || p == nil {
		t.Fatalf("translation not detected: generated=%v p=%v", generated, p)
	}
	if p.MTModel != "gpt-4o-mini" {
		t.Errorf("MTModel = %q, want gpt-4o-mini", p.MTModel)
	}
	if p.Src != "es" || p.Dst != "en" {
		t.Errorf("Src/Dst = %q/%q, want es/en", p.Src, p.Dst)
	}
	// This is the distinction that matters downstream: a machine translation
	// of a machine transcription is materially worse than either alone.
	if !p.Translated() {
		t.Error("Translated() = false for a track with an mt_model")
	}
}

// Files written before the rename exist in the wild forever, so the old
// marker must stay detected forever.
func TestConformanceLegacyMarker(t *testing.T) {
	generated, p := Detect(load(t, "legacy-marker.vtt"))
	if !generated {
		t.Fatal("a [stash-subs] file was not detected as generated")
	}
	if p == nil {
		t.Fatal("legacy marker detected but provenance not parsed")
	}
}

// The consequential direction: a false positive mislabels someone's hand-made
// subtitles as machine output.
func TestConformanceHumanWrittenIsNotGenerated(t *testing.T) {
	generated, p := Detect(load(t, "human.vtt"))
	if generated {
		t.Error("a hand-written subtitle was flagged as machine-generated")
	}
	if p != nil {
		t.Errorf("provenance parsed from a file with no marker: %+v", p)
	}
}

// Detection sniffs the first and last sniffBytes. On a long file the
// annotation cue sits well past the head window, so only the tail sniff finds
// it — the reason detection reads both ends rather than just the start.
func TestConformanceMarkerOnlyInTail(t *testing.T) {
	data := load(t, "marker-in-tail.vtt")
	if len(data) <= 2*sniffBytes {
		t.Fatalf("fixture is %d bytes; it must exceed 2×sniffBytes (%d) to exercise the tail",
			len(data), 2*sniffBytes)
	}
	if generated, _ := Detect(data); !generated {
		t.Error("marker in the tail was missed; the tail sniff is not working")
	}
}

// The documented blind spot. A marker in neither window is not found, and that
// is deliberate — sniffing the whole file would cost a full read on every
// upload. Pinned so changing the strategy is a decision, not an accident.
func TestConformanceMarkerBeyondSniffWindowIsMissed(t *testing.T) {
	data := load(t, "marker-buried.vtt")
	if len(data) <= 2*sniffBytes {
		t.Fatalf("fixture is only %d bytes; the marker would fall inside a window", len(data))
	}
	if generated, _ := Detect(data); generated {
		t.Log("a buried marker is now detected — if that was intentional, update this test")
		t.Error("detection scope changed unexpectedly")
	}
}
