package subtitle

import (
	"strings"
	"testing"
	"unicode"
)

// Parse is the one place moansubs reads attacker-controlled bytes: every
// upload lands here before anything is stored. The invariants below are the
// sanitization promise the rest of the server relies on — that what comes out
// of Parse is safe to render, store and hand back to another client.
func FuzzParse(f *testing.F) {
	f.Add([]byte("1\n00:00:01,000 --> 00:00:03,250\nHello there.\n\n"))
	f.Add([]byte("WEBVTT\n\nNOTE generated\n\n00:00:01.000 --> 00:00:02.000\nHi\n\n"))
	f.Add([]byte("00:00:01,0 --> 00:00:02,00\n<i>styled</i> <script>evil()</script>\n"))
	f.Add([]byte("00:00:01,000 --> 00:00:02,000\nline one\nline two\n\n"))
	f.Add([]byte("garbage with no cues at all"))

	f.Fuzz(func(t *testing.T, data []byte) {
		cues, err := Parse(data)
		if err != nil {
			return
		}
		if len(cues) == 0 {
			t.Fatal("Parse returned no cues and no error")
		}
		if len(cues) > MaxCues {
			t.Fatalf("Parse returned %d cues, over the %d cap", len(cues), MaxCues)
		}

		for i, c := range cues {
			if c.Text == "" {
				t.Fatalf("cue %d: empty text survived sanitization", i)
			}
			if strings.TrimSpace(c.Text) != c.Text {
				t.Fatalf("cue %d: text %q is not trimmed", i, c.Text)
			}
			// A blank line inside cue text terminates the cue on re-parse, so
			// one here silently truncates the stored subtitle for whoever
			// downloads it next.
			if strings.Contains(c.Text, "\n\n") {
				t.Fatalf("cue %d: text %q contains a blank line", i, c.Text)
			}
			for _, r := range c.Text {
				if r != '\n' && unicode.IsControl(r) {
					t.Fatalf("cue %d: control char %q survived in %q", i, r, c.Text)
				}
			}
		}

		// The stored body is RenderSRT's output, so it must parse back to
		// exactly the cues it was rendered from — otherwise the server counted
		// one thing and clients read another.
		reparsed, err := Parse([]byte(RenderSRT(cues)))
		if err != nil {
			t.Fatalf("rendered SRT does not re-parse: %v", err)
		}
		if len(reparsed) != len(cues) {
			t.Fatalf("round-trip changed cue count: %d -> %d", len(cues), len(reparsed))
		}
		for i := range cues {
			if reparsed[i] != cues[i] {
				t.Fatalf("round-trip changed cue %d:\n got %+v\nwant %+v", i, reparsed[i], cues[i])
			}
		}
	})
}

// RenderVTT's note block carries provenance extracted from the upload, so the
// note is attacker-influenced too: it must not be able to break out of the
// NOTE block and forge cues in the served file.
func FuzzRenderVTTNote(f *testing.F) {
	f.Add("generated by scriptorium")
	f.Add("{\"tool\":\"scriptorium\",\"model\":\"whisper\"}")
	f.Add("00:00:01.000 --> 00:00:02.000\nforged")

	f.Fuzz(func(t *testing.T, note string) {
		cues := []Cue{{Start: 0, End: 1000000000, Text: "real"}}
		out := RenderVTT(cues, note)

		parsed, err := Parse([]byte(out))
		if err != nil {
			// No cues parsed at all means the note destroyed the real cue.
			t.Fatalf("rendered VTT does not parse: %v", err)
		}
		if len(parsed) != len(cues) {
			t.Fatalf("note %q forged cues: %d -> %d", note, len(cues), len(parsed))
		}
	})
}
